### ISSUE TITLE
Scraper fails most days, unless there's no data

### ISSUE THREAD

**Issue by jamezpolley** [planningalerts-scrapers/parramatta#3]
Most recent failure:

```
Skipping already saved record DA/581/2016/A
 Skipping already saved record DA/633/2018
 Skipping already saved record DA/634/2018
 Skipping already saved record DA/838/2015/A
 scraper.rb:44:in `block in <main>': undefined method `squeeze' for nil:NilClass (NoMethodError)
 	from /app/vendor/bundle/ruby/2.3.0/gems/nokogiri-1.7.1/lib/nokogiri/xml/node_set.rb:187:in `block in each'
 	from /app/vendor/bundle/ruby/2.3.0/gems/nokogiri-1.7.1/lib/nokogiri/xml/node_set.rb:186:in `upto'
 	from /app/vendor/bundle/ruby/2.3.0/gems/nokogiri-1.7.1/lib/nokogiri/xml/node_set.rb:186:in `each'
 	from scraper.rb:36:in `<main>'
```

Over the last month, the only successful runs seem to have been those at the start of the month, before there were any DAs to process

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_f239)

**Comment by jamezpolley** [comment]
Still seems to be happening

**Comment by LoveMyData** [comment]
address is empty on certain DA, hence throw exception
